version: '3.3'
services:
  elasticsearch-three:
    container_name: elasticsearch-three
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8
    user: elasticsearch
    command: ["sh", "-c", "bin/elasticsearch-plugin list | grep -q discovery-ec2 || bin/elasticsearch-plugin install discovery-ec2 --batch && ./bin/elasticsearch"]
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata-one:/usr/share/elasticsearch/data
      - ./elasticsearch-one-config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

volumes:
  esdata-one:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/enc/db/elasticsearch1/data
