cluster.name: testindex
node.name: test-es-three
network.host: 0.0.0.0
network.publish_host: _ec2_
discovery.zen.hosts_provider: ec2
discovery.ec2.any_group: true
discovery.ec2.host_type: private_ip
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
discovery.ec2.tag.es_cluster: testindex-cluster
discovery.ec2.endpoint: ec2.us-east-1.amazonaws.com
node.master: true
discovery.zen.minimum_master_nodes: 3
plugin.mandatory: discovery-ec2
http.port: 9200
discovery.ec2.groups: sg-0cae955785d0c5ed2
